### ISSUE TITLE
Gradle Version Catalog

### ISSUE THREAD

**Issue by ddaeyeonkim** [JoyOfAndroid/study#18]
https://umang91.medium.com/version-catalogs-in-gradle-7-0-816873b59b47

**Comment by BeokBeok** [comment]
gradle은 생소해서 글을 봐도 뭐가 좋은지 잘 모르겠네요 ㅋㅋㅋ

**Comment by ddaeyeonkim** [comment]
#27 에서 완료

**Comment by BeokBeok** [comment]
아 이게 toml에 있는 카탈로그였군요 ㅋㅋㅋ
