### ISSUE TITLE
WindowInsetsAnimation 을 활용해서 키보드 제어하기

### ISSUE THREAD

**Issue by ddaeyeonkim** [JoyOfAndroid/study#6]
![1_9wELaIXfyzEQrHlsU2jkug](https://user-images.githubusercontent.com/36095102/154826071-246cef97-c2b3-452a-a655-68ef5a4b8327.gif)

**Comment by BeokBeok** [comment]
https://medium.com/androiddevelopers/animating-your-keyboard-reacting-to-inset-animations-839be3d4c31b
